config/routes.rb
Rails.application.routes.draw do

  #login
  root to: "sessions#new"
  resources :sessions, only: [:new, :create]
  get '/logout', to: 'sessions#logout', as: :logout


  #Register
  resources :users, only: [:new, :create]
  get "/registration_success", to: "users#success"

  #services
  resources :services
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :services
    has_secure_password

    validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Authentication
    # def current_user
    #   @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    # end
  
    # def action
    #   if current_user
    #     puts current_user
    #   else
    #     puts "not login"
    #   end
    # end
  end
  

app/controllers/concerns/authentication.rb
module Authentication   
    extend ActiveSupport::Concern
  
    included do
      before_action :current_user
      helper_method :current_user
      helper_method :user_signed_in?
    end
  
    def login(user)
      reset_session
      session[:current_user_id] = user.id
    end
  
  
    def redirect_if_authenticated
      redirect_to '/services', alert: "You are already logged in." if user_signed_in?
    end

    def redirect_if_not_authenticated
        redirect_to '/', alert: "You are not logged in." if !user_signed_in?
    end
  
    private
  
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
      end
  
    def user_signed_in?
      if current_user
        return true
      end
        return false
    end
  
  end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :redirect_if_not_authenticated

  def index
    @services = Service.where(user_id: current_user.id)
  end

  def new
    @service = Service.new
  end

  def create
    params[:service][:user_id] = current_user.id
    @service = Service.new(service_params)
    if validate_email_password
      puts service_params
      if @service.save
        redirect_to services_path, notice: "Service added successfully!"
      else
        render :new
      end
    else
      flash.now[:alert] = "Invalid email or password format."
      render :new, status: :unprocessable_entity
      # raise StandardError, "Invalid email or password format."
    end
  end
  

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
  
    if validate_email_password
      if @service.update(service_params)
        redirect_to services_path, notice: "Service updated successfully!"
      else
        render :edit
      end
    else
      flash.now[:alert] = "Invalid email or password format."
      render :edit, status: :unprocessable_entity
      # raise StandardError, "Invalid email or password format."
    end
  end


  private
  def service_params
    params.require(:service).permit(:name, :username, :password, :user_id)
  end
  
  private
  def validate_email_password
    email_pattern = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    password_pattern = /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$^&*])[A-Za-z\d!@#$^&*]{8,12}$/
  
    valid_email = email_pattern.match?(service_params[:username])
    valid_password = password_pattern.match?(service_params[:password])
    puts valid_email
    puts valid_password

    valid_email && valid_password
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_authenticated, only: [:create, :new]
  

  def new
    if current_user
      redirect_to '/services/new', notice: "Logged in successfully!"
    else
      puts "not login"
    end
  end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/services', notice: "Logged in successfully!"
    else
      flash.now[:alert] = "Invalid email or password. Please try again."
      render :new, status: :unprocessable_entity
    end
  end

  def logout
    reset_session
    redirect_to root_path, notice: "Logged out successfully!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_authenticated
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/registration_success'
    else
      flash.now[:alert] = "Invalid email or password format."
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasswordVault</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/edit.html.erb
<h1>Edit Service</h1>

<%= form_with model: @service, url: service_path(@service), method: :patch do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.submit "Update Service" %>
  </div>
<% end %>

app/views/services/index.html.erb
<h1>Services</h1>

<% if @services.any? %>
  <table>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th></th>
    </tr>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.username %></td>
        <td><%= service.password %></td>
        <td><%= link_to "Edit", edit_service_path(service) %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No services found.</p>
<% end %>

<%= link_to "Add Service", new_service_path %>

<%= link_to "Log out", '/logout' %>

app/views/services/new.html.erb
<h1>Add Service</h1>

<%= form_with model: @service, url: services_path, method: :post do |f| %>
    <%# <%= f.hidden_field :user_id, value: current_user.id %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.submit "Add Service" %>
  </div>
<% end %>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/users/create.html.erb
<h1>Registration Successful</h1>
<p>Thank you for registering!</p>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with model: @user, url: users_path, method: :post do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.email_field :username %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/success.html.erb
<h1>Registration Successful</h1>
<p>Thank you for registering!</p>